const questions = [
  {
    "question": "Choose a potion",
    "answer1": "Pink, shimmery potion that smells like cupcakes",
    "answer1Total": "6",
    "answer2": "Clear, bubbling potion that smells like popcorn ",
    "answer2Total": "1",
    "answer3": "Changes color between green and purple potion that smells like wine",
    "answer3Total": "4",
    "answer4": "Black potion with no smell",
    "answer4Total": "8",
    "answer5": "Who cares? Drink them all!",
    "answer5Total": "0"
  },
  {
    "question": "Which story would you like them to tell you",
    "answer1": "Romance between a couple who never grows old",
    "answer1Total": "0",
    "answer2": "Comedy an ogre who wants you to get out of his swamp",
    "answer2Total": "0",
    "answer3": "Tragedy about a wolf surgery gone wrong",
    "answer3Total": "0",
    "answer4": "A fairytale about a trippy experience in a shroom forest",
    "answer4Total": "10",
    "answer5": "I'd rather not",
    "answer5Total": "0"
  },
  {
    "question":
    "Pick something to eat",
    "answer1": "Travis Scott Burger",
    "answer1Total": "2",
    "answer2": "Waffles and Pancakes",
    "answer2Total": "0",
    "answer3": "Cereal and Orange Juice",
    "answer3Total": "5",
    "answer4": "Pickles coated in Nutella",
    "answer4Total": "4",
    "answer5": "PB&J with onions",
    "answer5Total": "10"
  },
  {
    "question": "Pick a song",
    "answer1": "Alice's Theme (the Appetizer)",
    "answer1Total": "3",
    "answer2": "Classic (Original)",
    "answer2Total": "2",
    "answer3": "Finesse (Expertise)",
    "answer3Total": "5",
    "answer4": "Time of our lives (Moment of our death)",
    "answer4Total": "8",
    "answer5": "Fpoba theme song (Willie Smitha)",
    "answer5Total": "0"
  },
  {
    "question": "Choose a healing method",
    "answer1": "Tylenol",
    "answer1Total": "4",
    "answer2": "Advil",
    "answer2Total": "5",
    "answer3": "Nyquil",
    "answer3Total": "6",
    "answer4": "Benadryl",
    "answer4Total": "9",
    "answer5": "Dayquil",
    "answer5Total": "0"
  },
  {
    "question":
      "What will you do to the white rabbit?",
    "answer1": "Yell at him",
    "answer1Total": "3",
    "answer2": "Dance with him",
    "answer2Total": "2",
    "answer3": "Eat him",
    "answer3Total": "0",
    "answer4": "Do nothing",
    "answer4Total": "9",
    "answer5": "Let him get away because you love the thrill",
    "answer5Total": "7"
  },
  {
    "question": "What is your rice purity?",
    "answer1": "0-25",
    "answer1Total": "6",
    "answer2": "26-50",
    "answer2Total": "4",
    "answer3": "51-75",
    "answer3Total": "2",
    "answer4": "76-100",
    "answer4Total": "0",
    "answer5": "What's that",
    "answer5Total": "8"
  },
  {
    "question": "Who is not coming to your tea party?",
    "answer1": "Mr. Hashimoto",
    "answer1Total": "5",
    "answer2": "Mr. Fulton",
    "answer2Total": "1",
    "answer3": "Mr. Peffer",
    "answer3Total": "0",
    "answer4": "Mr. Iglesias",
    "answer4Total": "9",
    "answer5": "Mrs. Sharma",
    "answer5Total": "7"
  },
  {
    "question": "Where are you leading your army of cards to?",
    "answer1": "700 Wing Bathroom (Males)",
    "answer1Total": "3",
    "answer2": "Eagle's Nest (Top of SAC)",
    "answer2Total": "8",
    "answer3": "Pool/Big Gym?",
    "answer3Total": "1",
    "answer4": "T4",
    "answer4Total": "0",
    "answer5": "Principal's Office",
    "answer5Total": "4"
  },
  {
    "question": "What place is 2021 getting in Spirit Week?",
    "answer1": "First place",
    "answer1Total": "0",
    "answer2": "#1",
    "answer2Total": "0",
    "answer3": "Winning",
    "answer3Total": "0",
    "answer4": "Numero Uno",
    "answer4Total": "0",
    "answer5": "4th in dances",
    "answer5Total": "0"
  }
]
